name: amase_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - rdkit
  - numba
  - astropy
  - gensim
  - pip
  - pip:
    - bokeh==2.4.3
    - fastdist
    - git+https://github.com/samoturk/mol2vec