# AMASE Configuration File Template
# Usage: python3 amase.py --config config_template.yaml

# ===== REQUIRED PARAMETERS =====

# Path to spectrum file (.txt format)
# First column: frequency (MHz), Second column: intensity
spectrum_path: "/path/to/spectrum.txt"

# Directory where files are stored and outputs will be saved
directory_path: "/path/to/working/directory/"

# Sigma threshold for line detection
# Code will only attempt to assign lines greater than sigma*rms noise
sigma_threshold: 5.0

# Experimental temperature in Kelvin
temperature: 2


# ===== OPTIONAL PARAMETERS =====

# Local catalogs configuration
local_catalogs_enabled: true
# If local_catalogs_enabled is true, you must provide:
local_directory: "/path/to/local/catalogs/"
local_csv_path: "/path/to/local_molecules.csv"
# The CSV must contain columns: name, smiles, iso

# Valid atoms that could be present in the mixture
# Options:
#   'default' - Uses C, O, H, N, S
#   'all' - Uses all atoms in periodic table
#   "C, O, H, N, S, P, F, Cl" - Comma-separated custom list
valid_atoms: "default"

# Whether to consider structural relevance
# If false, only spectroscopy will be considered
consider_structure: true

# SMILES strings of known molecular precursors
# Provide as comma-separated string like "c1ccccc1,C#N", or use "" for none
starting_molecules: ""


# ===== EXAMPLE CONFIGURATIONS =====

# Example 1: Basic configuration
# spectrum_path: "/home/user/data/spectrum_20250101.txt"
# directory_path: "/home/user/amase_results/"
# local_catalogs_enabled: false
# sigma_threshold: 5.0
# temperature: 10.0
# valid_atoms: "default"
# consider_structure: true
# starting_molecules: ""

# Example 2: With local catalogs and custom atoms
# spectrum_path: "/data/experiments/exp042/spectrum.txt"
# directory_path: "/data/experiments/exp042/"
# local_catalogs_enabled: true
# local_directory: "/home/user/local_catalogs/"
# local_csv_path: "/home/user/local_catalogs/molecules.csv"
# sigma_threshold: 3.5
# temperature: 77.0
# valid_atoms: "C, O, H, N, S, F, Cl"
# consider_structure: true
# starting_molecules: "CC(C)C, CCO"

# Example 3: All atoms, no structure consideration
# spectrum_path: "/mnt/data/spectrum_highres.txt"
# directory_path: "/mnt/data/analysis/"
# local_catalogs_enabled: false
# sigma_threshold: 4.0
# temperature: 150.0
# valid_atoms: "all"
# consider_structure: false
# starting_molecules: ""

# Example 4: With known precursors
# spectrum_path: "/lab/experiment_xyz/spectrum.txt"
# directory_path: "/lab/experiment_xyz/"
# local_catalogs_enabled: false
# sigma_threshold: 6.0
# temperature: 298.15
# valid_atoms: "default"
# consider_structure: true
# starting_molecules: "CC(=O)O, CCO, C"  # Acetic acid, Ethanol, Methane